user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    include /etc/nginx/conf.d/*.conf;

    client_body_temp_path /var/cache/nginx/client_temp;
    fastcgi_temp_path /var/cache/nginx/fastcgi_temp;
}